name: maps_demo
description: "Flutter maps/GPS demo"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  background_location: ^0.13.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
